### PR TITLE
Adding ELQ

### PR DESCRIPTION
**Pull request by belindal**
Adding ELQ.

Tested both BLINK functionality (getting comparable performance on benchmarks) and ELQ functionality.

How should we add ELQ to the README? (We could move each README to corresponding subdirectory and have main one link to both, or put everything on the main README?)

### CODE REVIEW

**Comment by fabiopetroni** [comment]
Thanks a lot @belindal :) Is there a README with instruction on how to use ELQ? Also, how can a pre-trained model on a sample input (maybe interactively)?

**Comment by belindal** [comment]
Sure! You can refer to the README on my master branch (https://github.com/belindal/BLINK/blob/master/README.md). (It's a bit messy, I'll have to clean it up before pushing). It has instructions on running pre-trained models.

**Comment by fabiopetroni** [comment]
Great. Can you put that in this pull request (maybe a bit cleaned). For now we can add a section in the main readme that points to that for ELQ. What do you think? Also, how can I test that everything is working, what command should I run?

**Comment by fabiopetroni** [comment]
Also, there is a ton of code replicated in the elq folder. Is that basically a clone of blink, or there is nested logic that is useful? In the ideal world elq will be a bunch of files on top of existing infra

**Comment by fabiopetroni** [comment]
Fantastic @belindal ! Thanks a lot :)

**Pull request merged**
